---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove: []
dockitems_persist:
- name: "Google Chrome"
  path: "/Applications/Google Chrome.app"
  pos: 2
- name: "Emacs"
  path: "/opt/homebrew/Cellar/emacs-plus@29/29.3/Emacs.app"
  pos: 3
- name: "Slack"
  path: "/Applications/Slack.app"
  pos: 4
- name: "GrandPerspective"
  path: "/Applications/GrandPerspective.app"
  pos: 5
- name: "iTerm"
  path: "/Applications/iTerm.app"
  pos: 6

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - autoconf
  - bash-completion
  - git
  - go
  - gpg
  - iperf
  - sqlite
  - nmap
  - fnm
  - cowsay
  - readline
  - openssl
  - wget
  - aspell
  - the_silver_searcher
  - stats
  - make
  - diffutils
  - emacs-plus@29

homebrew_taps:
  - d12frosted/emacs-plus

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - chromedriver
  - docker
  - dropbox
  - firefox
  - google-chrome
  - slack
  - iterm2
  - gimp
  - visual-studio-code
  - stats
  - adobe-acrobat-reader
  - rectangle
  - grandperspective
  - graphiql

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
