---
- name: Autohide the dock
  shell: defaults write com.apple.dock "autohide" -bool "true" && killall Dock

- name: Show hidden files in finder
  shell: defaults write com.apple.finder "AppleShowAllFiles" -bool "true" && killall Finder
