---
- name: Get Dotfiles
  git:
    repo: https://github.com/flyck/dotfiles.git
    dest: ~/dotfiles
    update: yes

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh

- name: Copy .zshrc
  copy:
    src: ~/dotfiles/.zshrc
    dest: ~/.zshrc

- name: Get themes
  git:
    repo: https://github.com/mbadolato/iTerm2-Color-Schemes
    dest: /tmp/iterm2-color-schemes

- name: Only import themes once
  stat: path=.themes_installed
  register: themes_installed

- name: Import Iterm2 themes
  shell: tools/import-scheme.sh schemes/*
  args:
    chdir: /tmp/iterm2-color-schemes
  when: themes_installed.stat.exists == False

- name: Creating an empty file
  file:
    path: ".themes_installed"
    state: touch
