---
- name: Get Dotfiles
  git:
    repo: https://github.com/flyck/dotfiles.git
    dest: ~/dotfiles
    update: yes

- name: Install oh-my-zsh
  # TODO didnt work, needed to be executed manually (/bin/sh not found)
  command: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh

- name: Copy .zshrc
  copy:
    src: ~/dotfiles/.zshrc
    dest: ~/.zshrc

- name: Get themes
  git:
    report: https://github.com/mbadolato/iTerm2-Color-Schemes
    dest: /tmp/iterm2-color-schemes

- name: Import Iterm2 themes
  command: tools/import-scheme.sh schemes/*
