---
- name: Get Dotfiles
  git:
    repo: https://github.com/flyck/dotfiles.git
    dest: ~/dotfiles
    update: yes

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: ~/.oh-my-zsh

- name: Copy .zshrc
  copy:
    src: ~/dotfiles/.zshrc
    dest: ~/.zshrc

# trying to import that the dynamical profile folder gave an error
- name: Copy iterm profile
  copy:
    src: files/terminal/profile.json
    dest: ~/Desktop/iterm_profile.json

- name: Only import themes once
  stat: path=.themes_installed
  register: themes_installed

- name: Get Font for starship prompt
  block:
  - name: Ensure fonts directory
    file:
      path: "{{ lookup('env', 'HOME') }}/.fonts"
      state: directory

  - name: Hack exists
    shell: "ls {{ lookup('env', 'HOME') }}/.fonts/Hack*Nerd*Font*Complete*"
    register: hack_exists
    ignore_errors: yes

  - name: Download Hack
    when: hack_exists is failed
    ansible.builtin.unarchive:
      src: https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/Hack.zip
      dest: "{{ lookup('env', 'HOME') }}/.fonts/"
      remote_src: yes

- name: Get terminal themes
  when: themes_installed.stat.exists == False
  block:
    - name: Get the theme color repo
      git:
        repo: https://github.com/mbadolato/iTerm2-Color-Schemes
        dest: /tmp/iterm2-color-schemes

    - name: Import Iterm2 themes
      shell: tools/import-scheme.sh schemes/*
      args:
        chdir: /tmp/iterm2-color-schemes

    - name: Creating an empty file
      file:
        path: ".themes_installed"
        state: touch
